inject/src/main/java/io/avaje/inject/ApplicationScope.java
inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/RequestScope.java

Use withShutdownHook(true) on BeanScopeBuilder as needed.

Default shutdown hook to false for BeanScope

---

inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java

The compilation failed because the parameter type was not imported.

Parameter type import of aspect method.

---

README.md

Add Quick Start to README

---

inject-generator/src/main/java/io/avaje/inject/generator/GenericType.java
inject-test/src/test/java/org/example/generic/EventBus.java
inject-test/src/test/java/org/example/generic/EventBusImpl.java
inject-test/src/test/java/org/example/generic/Subscriber.java

Fix shortName generation with wildcards

---

README.md

made a discord for easier discussions/troubleshooting

discord badge

---

inject/pom.xml
jakarta-to-javax.sh
javax-to-jakarta.sh

With the view of maintaining the javax fork via scripts rather than the javax.master branch

Add scripts to perform Jakarta to Javax conversion (jakarta-to-javax.sh) 

---

inject-generator/pom.xml
inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeAnnotationReader.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
inject-generator/src/main/java/io/avaje/inject/generator/Util.java

As the title says. It does need 1.4 to be deployed though.

Use Prisms 1.4 IsPresent

---

inject-generator/src/main/java/io/avaje/inject/generator/PrimitiveUtil.java
inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
inject-generator/src/main/java/io/avaje/inject/generator/package-info.java

Support Wiring Primitives

---

inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
inject-generator/src/main/java/io/avaje/inject/generator/package-info.java
inject-test/src/test/java/org/example/autonamed/MyAutoB2.java
inject-test/src/test/java/org/example/autonamed/MyAutoB2Explicit.java
inject/src/main/java/io/avaje/inject/Component.java

Adds an annotation to import types and generate DI classes for them.

Component Import Annotaion

---

README.md
inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
inject-generator/src/main/java/io/avaje/inject/generator/RequestScope.java
inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/spi/Plugin.java

Who really doesn't want to see how fast everything wires?

Log Wiring Time

---

inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java

Use Single ThreadLocal in Processor

---

README.md

The compiler plugin stuff isn't really needed for a quick start

Make quickstart even quicker

---

inject/src/main/java/io/avaje/inject/spi/Plugin.java

Suppose you want to create a plugin that doesn't create beans.

Make Plugin Provides a Default Method.

---

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java

We can use non-nullable get() for the factory when we know there are no conditions on the factory,
rather than always use getNullable()

Tidy code generation for conditions on factory

---

README.md
jakarta-to-javax.sh
javax-to-jakarta.sh

So that people don't accidentally run into #332

Update module example

---

inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java

Now can add scope hooks on the BeanScope builder

---

blackbox-aspect/src/main/java/org/example/external/aspect/MyExternalAspect.java
blackbox-test-inject/src/main/java/org/example/myapp/Main.java
inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java
inject-generator/src/main/java/io/avaje/inject/generator/package-info.java
inject/src/main/java/io/avaje/inject/aop/Aspect.java

Adds an annotation that marks the given annotation as an aspect.

Aspect.Import Annotation

---

blackbox-test-inject/src/test/java/org/example/myapp/HelloServiceTest.java
blackbox-test-inject/src/test/java/org/example/myapp/r4j/Resilience4J_retry_Test.java
inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java
inject/src/main/java/io/avaje/inject/aop/InvocationException.java

Proxy methods now add suppressed exceptions to Unchecked Exceptions

---

inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java

- Add SuppressWarnings unchecked
- Return early to remove empty if block
- Remove some whitespace and format

No effective change - tidy TypeExtendsReader

---

inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
inject/src/main/java/io/avaje/inject/spi/DBuilder.java

Instead of allocating a new optional empty for every bean.

Constant Empty Optional

---

inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
inject-generator/src/test/java/io/avaje/inject/generator/ScopeInfoTest.java

#356 - Test and refactor for - Fix Generic type Params showing up in generated requires

---

inject/src/main/java/io/avaje/inject/DConfigProps.java
inject/src/main/java/io/avaje/inject/DSystemProps.java

We don't really need them with the default methods

Remove Superflous ConfigProp methods

---

blackbox-test-inject/src/main/java/org/example/myapp/HelloService.java
inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/spi/Builder.java
inject/src/main/java/io/avaje/inject/spi/DBeanScope.java
inject/src/main/java/io/avaje/inject/spi/DBuilder.java

Now can access the completed BeanScope from post construct methods
```
@PostConstruct
void postCon(BeanScope scope) {
}
```

BeanScope PostContruct

---

blackbox-test-inject/src/main/java/org/example/myapp/profile/Bettas.java
blackbox-test-inject/src/main/java/org/example/myapp/profile/Fish.java
blackbox-test-inject/src/main/java/org/example/myapp/profile/FishFactory.java
blackbox-test-inject/src/main/java/org/example/myapp/profile/FishProfile.java
blackbox-test-inject/src/test/java/org/example/myapp/conditional/ConditionalTests.java
blackbox-test-inject/src/test/java/org/example/myapp/profile/ProfileTests.java
inject-generator/src/main/java/io/avaje/inject/generator/BeanConditions.java
inject-generator/src/main/java/io/avaje/inject/generator/ConditionalWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/package-info.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/profile/Bettas.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/profile/Fish.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/profile/FishFactory.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/profile/FishProfile.java
inject/src/main/java/io/avaje/inject/Profile.java
inject/src/main/java/io/avaje/inject/spi/Builder.java
inject/src/main/java/io/avaje/inject/spi/DBuilder.java
inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java
inject/src/main/java/module-info.java

Adds a `@Profile` annotation for conditional wiring. Solves #304 from a certain point of view.

Add support for `@Profile` annotation - conditional wiring via profiles

---

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java
inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java
inject-test/src/main/java/io/avaje/inject/test/InjectTest.java

Let me tell ya, it's much easier to troubleshoot `autorequires` issues if we have this.

Auto Requires Logging

---

blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java
blackbox-test-inject/src/test/java/org/example/myapp/profile/ProfileTests.java
inject-test/src/main/java/io/avaje/inject/test/InjectTest.java
inject-test/src/main/java/io/avaje/inject/test/MetaInfo.java
inject/src/main/java/io/avaje/inject/DConfigProps.java
inject/src/main/java/io/avaje/inject/DSystemProps.java
inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java

Now can set wiring profile with @InjectTest

InjectTest profiles

---

inject-test/src/main/java/io/avaje/inject/test/MetaInfo.java
inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/spi/Builder.java
inject/src/main/java/io/avaje/inject/spi/DBuilder.java
inject/src/main/java/io/avaje/inject/spi/DBuilderExtn.java

Use Var-Args for profiles

---

inject-generator/pom.xml
inject-generator/src/main/java/io/avaje/inject/generator/AllScopes.java
inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java
inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java
inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeAnnotationReader.java
inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
inject/src/main/java/io/avaje/inject/Component.java
inject/src/main/java/io/avaje/inject/InjectModule.java

Use the generated APContext from prisms

Prisms 1.14

---

README.md

Add Spring DI Table

---

inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java
inject-generator/src/main/java/io/avaje/inject/generator/Util.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/UserMaker.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/_Wiring.java

Normalize Invalid @Named characters

---

README.md
pom.xml

Enable Annotation processing in 22

---

blackbox-test-inject/src/test/java/org/example/myapp/MyDestroyOrderTest.java
inject-test/src/test/java/org/example/custom/CustomScopeTest.java

in a newer version http added a plugin

Fix CustomScope Test

---

inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
inject/src/main/java/io/avaje/inject/aop/Aspect.java

now we can register multiple in a single class/package/module-info

Make `@Aspect.Import` Repeatable

---

.github/dependabot.yml
blackbox-test-inject/pom.xml
inject-test/pom.xml

Adds support for JDK 23 early access versions

Support JDK 23-EA

---

blackbox-test-inject/pom.xml
inject-generator/pom.xml
inject-test/pom.xml
inject/pom.xml
pom.xml

Bump parent pom to 4.1 with maven-surefire-plugin byte-buddy JDK 23 support

---

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java

Add http validator to autodetected plugins

---

inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
inject/src/main/java/io/avaje/inject/spi/Builder.java
inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
inject/src/main/java/io/avaje/inject/spi/DBuilder.java
inject/src/main/java/io/avaje/inject/spi/DContextEntry.java
inject/src/main/java/io/avaje/inject/spi/DContextEntryBean.java
inject/src/test/java/io/avaje/inject/spi/DContextEntryTest.java

Based on #549 but move current module into DBeanMap

Prefer intra-module beans when resolving type (v2)

---

inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java
inject-generator/src/main/java/io/avaje/inject/generator/Util.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/EventSender.java
inject-test/src/test/java/org/example/observes/EventSender2.java
inject-test/src/test/java/org/example/observes/MyObserver2.java
inject-test/src/test/java/org/example/observes/MyStrQualifiedObserver.java
inject-test/src/test/java/org/example/observes/StrQualifier.java
inject-test/src/test/java/org/example/observes/TestEventMessaging.java

Fix escape quotes on Event with qualifiers with string members (otherwise compiler error)

---

blackbox-test-inject/src/main/java/org/example/myapp/ListFactory.java
blackbox-test-inject/src/main/java/org/example/myapp/ListService.java
blackbox-test-inject/src/test/java/org/example/myapp/ListFactoryTest.java
inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/ListFactory.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/SomethingService.java

Now can do:
```java
@Factory
public class ListFactory {
@Bean
List<String> test() {
return List.of("test1", "test2");
}
@Bean
String test3() {
return "test3";
}
}
```
and get `"test1", "test2","test3"` when injecting a `List<String>`. (Even Spring cannot do this currently)

Multi-register beans with `List` Factory Methods

---

blackbox-test-inject/src/main/java/org/example/myapp/other/ConfigFactory.java
blackbox-test-inject/src/test/java/org/example/myapp/other/ConfigFactoryTest.java
inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java
inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java
inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java
inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
inject-generator/src/main/java/io/avaje/inject/generator/Util.java
inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java
inject-generator/src/test/java/io/avaje/inject/generator/models/valid/ConfigFactory.java

Fix Factory Map generation

---

.github/workflows/build.yml
.github/workflows/jdk-ea.yml

It seems we need to add it so that it runs on PRs created from forks

Change workflow to run on forked PRs

---

inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java

- now will generate method return types with the short type
- use common Class variable for the target class

Simplify Generated Proxy Classes

---

inject-generator/src/main/java/io/avaje/inject/generator/AssistBeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
inject-generator/src/main/java/io/avaje/inject/generator/EventPublisherWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleAssistWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/SimpleOrderWriter.java
inject-generator/src/main/java/io/avaje/inject/generator/Util.java
inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java

Remove unused generated imports
After this we should be good for 10.x

Update Generated Imports

---

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java

Add avaje-http jstache plugin to autodetected Plugins 

---

inject-events/src/main/java/io/avaje/inject/events/Event.java

[events] Use runAsync

---

jakarta-to-valhalla.sh
pom.xml

sed in CI works a little differently??  Ah the old Mac OS/Darwin difference with `-i` ... dang it.

Update Valhalla build, sed use explicit current dir?

---

inject/src/main/java/io/avaje/inject/Prototype.java

PR for https://github.com/avaje/avaje-inject/issues/746

Use runtime retention in Prototype annotation

---

inject/src/main/java/io/avaje/inject/RequiresBean.java

Fixes a javadoc issue with use of link

javadoc only - RequiresBean use code instead of link

---

inject-test/pom.xml

Saw strange behavior when I tried excluding the events dependency and running tests.

[test] remove hard dependency on events

---

.github/workflows/build.yml

Yeah this artifact compare thing doesn't seem to be doing all that much

speed up build

---

inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java
inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java

Now will read the plugin provides annotation values with the maven/gradle plugin

Read `@PluginProvides` Annotation with Maven Plugin
