inject/pom.xml, inject/src/main/java/io/avaje/inject/core/DBeanContext.java
Use reflection to find javax.annotation.Priority, thus making the javax.annotation-api dependency optional.
=> Make javax.annotation-api dependency optional

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-test/src/test/java/org/example/coffee/fruit/AppleService.java, inject-test/src/test/java/org/example/request/AController.java, inject-test/src/test/java/org/example/request/JexController.java
This is a missing feature I stumbled across when attempting to convert a project from Guice, which supports `@Inject` on methods.
I tweaked a few classes in the inject-test module to use method injection instead of field injection and the unit tests all still passed.
I also examined the generated code and it seemed correct to me, so hopefully I didn't miss anything.
=> Add support for method based injection.

inject-test/src/test/java/org/example/coffee/factory/Configuration.java, inject/src/main/java/io/avaje/inject/PostConstruct.java, inject/src/main/java/io/avaje/inject/PreDestroy.java
We can use any `@PostConstruct` or `@PreDestory` annotation.  Adding these as avaje inject annotations means that people don't need to depend on the JEE javax.annotation or jakarta.annotation for these annotations.
That is, we consider them important enough to have our own (and dependency on jakarta.annotation for these is not ideal).
=> Add io.avaje.inject @PostConstruct/@PreDestroy annotations

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Constants.java, inject-generator/src/main/java/io/avaje/inject/generator/IncludeAnnotations.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-test/pom.xml
1. Allow PostConstruct/PreDestory annotations from other packages.
2. Remove javax.annotation-api dependency since it is no longer strictly required.
=> Tweaks for PostConstruct/PreDestory changes

inject/src/main/java/io/avaje/inject/spi/DBeanContext.java
1. Don't allow null priorityAnnotation since consumers now pass it in instead of allowing it to be reflectively discovered.
2. Only used directly declared instances of Priority annotations and not those of any superclasses.
=> More annotation-api tweaks

inject-test/src/test/java/io/avaje/inject/BeanContextBuilderTest.java, inject-test/src/test/java/org/example/coffee/BeanContextBuilderAddTest.java, inject-test/src/test/java/org/example/coffee/BeanContext_Builder_mockitoSpyTest.java, inject-test/src/test/java/org/example/coffee/CoffeeMakerTest.java, inject-test/src/test/java/org/example/coffee/ExtensionExample.java, inject-test/src/test/java/org/example/coffee/ExtensionExampleTest.java, inject-test/src/test/java/org/example/coffee/FactoryTest.java, inject-test/src/test/java/org/example/coffee/InjectListTest.java, inject-test/src/test/java/org/example/coffee/ProviderTest.java, inject-test/src/test/java/org/example/coffee/circular/CircularDependencyTest.java, inject-test/src/test/java/org/example/coffee/factory/AFactTest.java, inject-test/src/test/java/org/example/coffee/factory/BFactTest.java, inject-test/src/test/java/org/example/coffee/factory/ConfigurationTest.java, inject-test/src/test/java/org/example/coffee/factory/MultipleOtherThingsTest.java, inject-test/src/test/java/org/example/coffee/factory/MyFactoryTest.java, inject-test/src/test/java/org/example/coffee/fruit/AppleServiceTest.java, inject-test/src/test/java/org/example/coffee/generic/HazManagerTest.java, inject-test/src/test/java/org/example/coffee/grind/AMusherTest.java, inject-test/src/test/java/org/example/coffee/grind/BMusherTest.java, inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithFieldQualifierTest.java, inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithNamedTest.java, inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithQualifierTest.java, inject-test/src/test/java/org/example/iface/NestedInterfaceTest.java, inject/src/main/java/io/avaje/inject/BeanContext.java, inject/src/main/java/io/avaje/inject/BeanContextBuilder.java, inject/src/main/java/io/avaje/inject/DBeanContextBuilder.java, inject/src/main/java/io/avaje/inject/SystemContext.java, inject/src/test/java/io/avaje/inject/BeanContextBuilderTest.java
Refactor to make the api more abstract by changing BeanContextBuilder to be an interface.
Breaking change, we need to change `new BeanContextBuilder()` to be `BeanContext.newBuilder()`
=> Refactor BeanContextBuilder extract interface, use static newBuilder()

inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
To avoid "Missing @DependencyMeta on method build" error on partial rebuild
=> Opps, use build_ prefix for reading meta data annotations from build methods

inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
Please review and merge if you agree :)
=> bugfix for https://github.com/avaje/avaje-inject/issues/177

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java, inject-test/src/test/java/org/example/coffee/InjectListTest.java, inject-test/src/test/java/org/example/coffee/list/SomeInterface.java, inject-test/src/test/java/org/example/coffee/list/SomeInterfaceConsumer.java
Hi,
here is the PR for https://github.com/avaje/avaje-inject/issues/179.
Thanks
=> added fix and test for #179

blackbox-test-inject/pom.xml, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeUtil.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject-test/pom.xml, inject-test/src/test/java/org/example/coffee/BeanScopeBuilderAddTest.java, inject/pom.xml, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/InjectModule.java, inject/src/main/java/io/avaje/inject/spi/Module.java, inject/src/test/java/io/avaje/inject/BeanScopeBuilderTest.java, pom.xml
This means that we don't need to reference each and every dependency in requires and instead can put one
into requiresPackages such that any dependency in that package or a subpackage of that package is deemed
to be supplied by another module.
=> #193 - Add @InjectModule requirePackages ... for better multi-module requires/provides

blackbox-test-inject/pom.xml, inject-generator/pom.xml, inject-test/pom.xml, inject-test/src/test/java/org/example/circular/CupholderTest.java, inject-test/src/test/java/org/example/generic/repo/AbstractRepo.java, inject-test/src/test/java/org/example/generic/repo/GenericWithMockTest.java, inject-test/src/test/java/org/example/generic/repo/MapRepo1.java, inject-test/src/test/java/org/example/generic/repo/MapRepo2.java, inject-test/src/test/java/org/example/generic/repo/MapService.java, inject-test/src/test/java/org/example/generic/repo/MapService1.java, inject-test/src/test/java/org/example/generic/repo/MapService2.java, inject-test/src/test/java/org/example/generic/repo/Model1.java, inject-test/src/test/java/org/example/generic/repo/Model2.java, inject-test/src/test/java/org/example/generic/repo/ServiceClass.java, inject/pom.xml, inject/src/main/java/io/avaje/inject/spi/DBeanMap.java, pom.xml
The core fix is with DBeanMap. In detail, when wiring mocks/spy this part of DBeanMap additionally registers the mock with the generic type (which is in the generated code).
Prior to this fix, this process was too loose and registered the mock with other types like Model2 in the test case.
=> #243 - Fix for ClassCastException with generic types

.gitignore, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java
Now for this class.
```
@MyTimed
@Singleton
public class ExampleService {
@MyAround
public String other(
String param0, int param1) { // } throws IOException, IllegalStateException {
return "other " + param0 + " " + param1;
}
}
```
Generates
```
@Proxy
public class ExampleService$Proxy extends ExampleService {
private final MyAroundAspect myAroundAspect;
private final MyTimedAspect myTimedAspect;
private Method other0;
private MethodInterceptor other0MyAround;
private MethodInterceptor other0MyTimed;
public ExampleService$Proxy(MyAroundAspect myAroundAspect, MyTimedAspect myTimedAspect) {
super();
this.myAroundAspect = myAroundAspect;
this.myTimedAspect = myTimedAspect;
try {
other0 = ExampleService.class.getDeclaredMethod("other", String.class, …
```
=> Now class aspects are included with method aspects

inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectPair.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanAspects.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java, inject/src/main/java/io/avaje/inject/aop/Aspect.java
- Changed generated aspect proxy class to use AspectProvider Interface
- Changed Aspect Annotation to only accept types extending AspectProvider.
- Removed unused fields in generated proxy class
Example generated proxy class:
```
@Proxy
public final class ServiceClass$Proxy extends ServiceClass {
private final TimedAspect timedAspect;
private Method callDownStream0;
private MethodInterceptor callDownStream0Timed;
public ServiceClass$Proxy(TimedAspect timedAspect, ApiClient api) {
super(api);
this.timedAspect = timedAspect;
try {
callDownStream0 = ServiceClass.class.getDeclaredMethod("callDownStream");
callDownStream0Timed = timedAspect.interceptor(callDownStream0, callDownStream0.getAnnotation(Timed.class));
} catch (Exception e) {
throw new …
```
=> Use Aspect Provider instead of Concrete Aspect Target

inject-generator/src/main/java/io/avaje/inject/generator/AspectAnnotationReader.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectPair.java, inject-generator/src/main/java/io/avaje/inject/generator/Constants.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/spi/Module.java
Now modules can automatically provide aspects for use in other modules without directly exposing the underlying aspect target.
- Modifies the ExternalProvider to read the `autoProvidesAspects` from loaded modules
- adds `autoRequiresAspects` to Module Class
- updates DBeanScopeBuilder to read the autoRequiresAspects and use it for module ordering.
Fixes #269 (nice)
Now that I consider it, do we even need the target field in the `@Aspect` annotation anymore?
=> Add Aspect Auto Requires

inject-generator/pom.xml
This would actually fix the #281 issue with Jsonb. Though we still need to create a grade plugin for non-annotation processor dependencies
=> Inject is no longer an optional dependency for generators

inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java, inject-generator/src/main/java/io/avaje/inject/generator/GenericType.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-test/src/test/java/io/avaje/inject/xtra/ApplicationScope.java, inject-test/src/test/java/org/example/MyCustomScope.java, inject-test/src/test/java/org/example/coffee/CoffeeMaker.java, inject-test/src/test/java/org/example/custom/CustomScopeTest.java, inject-test/src/test/java/org/example/custom2/OciMarker.java, inject/src/main/java/io/avaje/inject/BeanScope.java, inject/src/main/java/io/avaje/inject/spi/DBeanScope.java, inject/src/main/java/io/avaje/inject/spi/DBeanScopeProxy.java, inject/src/test/java/io/avaje/inject/BeanScopeBuilderTest.java
- remove registering beans by annotation
- modifies listByAnnotation to find the annotated beans at runtime (only seems to work with annotations with `@Retention(RetentionPolicy.RUNTIME)` )
- fixes generation bug where annotating inject constructor params throws errors
fixes #285
=> Now doesn't register beans by annotations

inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/spi/Plugin.java
Change BeanScopeBuilder.provideDefault() to use Supplier rather than Provider as then the Plugin implementation is tied to either the jakarta or javax version it is compiled against.
=> To make Plugins support both jakarta and javax versions we need to use Supplier

blackbox-test-inject/pom.xml
Prior to this avaje-jsonb only supported the jakarta version of avaje-inject
=> Bump test dependency avaje-jsonb to 1.3-RC2 to support both javax and jakarta

inject-maven-plugin/pom.xml
looks like the format plugin was the cause of the EA failures, in any case, the code is already formatted fine so we can toss it.
=> Remove Format Plugin

inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-test/src/test/java/org/example/coffee/list/CombinedMapSomei.java, inject/src/main/java/io/avaje/inject/QualifiedMap.java
Well, I didn't know that map wiring was originally only for getting qualified beans. Seems like a pretty uncommon use case compared to wiring regular maps.
- adds @QualifiedMap annotation to make generated DI classes have the old behavior
- modifies util methods to use regular `builder.get` unless the Map has the annotation.,
fixes #298
=> Support Wiring Regular Maps

blackbox-test-inject/src/main/java/org/example/myapp/aspect/MyBefore.java, blackbox-test-inject/src/main/java/org/example/myapp/aspect/MyMultiInvoke.java, blackbox-test-inject/src/main/java/org/example/myapp/aspect/MySkip.java, blackbox-test-inject/src/main/java/org/example/myapp/aspect/MyThrowing.java, blackbox-test-inject/src/main/java/org/example/myapp/aspect/MyTimed.java, blackbox-test-inject/src/main/java/org/example/myapp/resilience4j/MyRetry.java, inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-test/src/test/java/org/example/coffee/list/CombinedMapSomei.java, inject/src/main/java/io/avaje/inject/BeanScope.java, inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/QualifiedMap.java, inject/src/main/java/io/avaje/inject/aop/Aspect.java
If we're bumping major versions, let's remove the deprecated stuff.
Deprecated methods removed are:
```java
public @interface Aspect {
/**
* Deprecated - the target() attribute is no longer required and should be removed.
*/
@Deprecated
Class<?> target() default Void.class;
```
```java
/**
* Deprecated - migrate to builder().
*/
@Deprecated
static BeanScopeBuilder newBuilder()
```
```java
/**
* Deprecated - migrate to shutdownHook().
*/
@Deprecated
default BeanScopeBuilder withShutdownHook(boolean shutdownHook)
```
```java
/**
* Deprecated - migrate to modules()
*/
@Deprecated
default BeanScopeBuilder withModules(Module... modules)
```
```java
/**
* Deprecated - migrate to bean().
*/
@Deprecated
default <D> BeanScopeBuilder withBean(Class<D> type, D bean)
```
```java
/**
* Deprecated - …
```
=> Remove Deprecated Methods

inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject/src/main/java/io/avaje/inject/spi/DBeanScopeProxy.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java
Now can access currently registered beans while the scope is being built.
Also fixes #306
=> Give BeanScopeProxy access to Builder

inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java
So after all this autoRequires stuff, wouldn't it be easier to have avaje auto add nullable types to auto requires instead of 
needing to manually define `@InjectModule(requires={X,Y,Z})` for every single nullable bean?
- Adds a static set to ProcessingContext that we can use to keep track of nullable/optional types
- Update Field and Method Readers to add the bean type to the set when nullable or Optional Type is detected
- Fixes Proxy Writer not writing `@Nullable` annotations when needed 
Fixes https://github.com/avaje/avaje-inject/issues/244
=> Auto add nullable beans to auto-requires/Fix Proxy not writing `@Nullable`

.github/workflows/build.yml, blackbox-test-inject/pom.xml, jakarta-to-javax.sh, javax-to-jakarta.sh
I for one welcome our new AI overlords.
- Will add/remove `-javax` from the parent version (will even work on RC versions)
- Now correctly replaces javax when going back to jakarta.
- update GitHub actions to test javax build.
=> Update Javax/Jakarta Scripts to Add/Remove `-javax` in Parent Version.

blackbox-test-inject/src/main/java/org/example/myapp/conditional/BirdFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/conditional/BirdWatcher.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanConditions.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject/src/main/java/io/avaje/inject/RequiresBean.java, inject/src/main/java/io/avaje/inject/RequiresProperty.java, inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java
- Read the repeatable Container annotations
- Move the annotation reading into BeanConditions
- Rename the inner repeatable annotations to Container (so IDE autocompletion for Requires* only sees our 2 @RequiresBean and @RequiresProperty annotations
=> #312 Follow up for @Requires - read repeatable container annotations

jakarta-to-javax.sh, pom.xml
Brought to you by ChatGPT.
>In summary, this sed command uses regular expressions to match and replace the first occurrence of `<version>...</version>` in the file. If the original version contains the -SNAPSHOT suffix, it adds the -javax suffix before the -SNAPSHOT suffix. If the original version doesn't contain the -SNAPSHOT suffix, it adds the -javax suffix after the version number.
=> Now Scripts will Add/Remove `-javax` even if there is no `-SNAPSHOT`

blackbox-test-inject/src/main/java/org/example/myapp/conditional/BirdFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/conditional/BirdWatcher.java, blackbox-test-inject/src/main/java/org/example/myapp/conditional/NoKiwi.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanConditions.java, inject/src/main/java/io/avaje/inject/RequiresBean.java, inject/src/main/java/io/avaje/inject/RequiresProperty.java
- fix javadocs
- rename methods to missing (because prop/bean annotations are separate I'd say there are enough context clues)
=> Update Requires Javadoc/Rename Missing Methods

blackbox-test-inject/src/main/java/org/example/myapp/conditional/BirdFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/conditional/Finches.java, blackbox-test-inject/src/main/java/org/example/myapp/conditional/NoFinches.java, blackbox-test-inject/src/test/java/org/example/myapp/ConditionalTests.java, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/BeanConditions.java, inject/src/main/java/io/avaje/inject/RequiresBean.java, inject/src/main/java/io/avaje/inject/RequiresProperty.java
Now can get even more meta with the annotations. Observe:
```
@RequiresBean(Bird.class)
@RequiresProperty(value = "watcher", equalTo = "bird")
public @interface RequiresBirdWatcher {}
```
```
@RequiresBirdWatcher
@RequiresProperty(value = "whale.whale.whale", equalTo = "what do we have here")
public @interface RequiresWatcherAndWhale {}
```
```
@Singleton
@RequiresWatcherAndWhale
public class OtherClass {
...
}
```
The generator will read all the meta-annotations and correctly add the conditions. 
This relies on [avaje-prisms 1.6](https://github.com/avaje/avaje-prisms/pull/11) being deployed.
=> Support Meta-Annotations on Meta-Annotations

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
=> Use ThreadLocal ProcessingContext

inject-generator/src/main/java/io/avaje/inject/generator/AllScopes.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
This adds the limitation that custom scopes can not support other annotation processors generating beans that have those custom scopes.
=> Write Custom modules early (not in last round of processing)

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
Okay so stay with me here, I'm thinking that we could expose the propertyPlugin from the builder and use that to help configure avaje plugins based on properties alone.
For example:
```java
public final class AvajePlugin implements io.avaje.inject.spi.Plugin {
@Override
public Class<?>[] provides() {
return new Class<?>[]{SomeClass.class};
}
@Override
public void apply(BeanScopeBuilder builder) {
if( builder.propertyPlugin().contains("prop")) {
// register something
};
}
}
```
=> Expose PropertyPlugin from BeanScopeBuilder

blackbox-test-inject/pom.xml, blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java, inject-generator/pom.xml, inject/src/main/java/io/avaje/inject/DSystemProps.java, inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java
I'm thinking it would be even more useful for plugins if they could get the bean scope's properties without needing any config dependencies.
=> Add get method to Property Plugin

inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
I guess the URL contructors are deprecated in JDK 20
=> use URI instead of URL contructor

blackbox-test-inject/pom.xml, inject/pom.xml, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DConfigProps.java, inject/src/main/java/module-info.java
Due to module-path working differently to classpath wrt optional services we need to make this change to enable avaje-config to not have a hard dependency on avaje-inject in module-path.
=> #336 - Fix dependency relationship with avaje-config

inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
Due to module-path working differently to classpath wrt optional services we need to make this change. Otherwise avaje-inject becomes a hard dependency required by avaje-config, avaje-jsonb, any Plugin in fact.
We desire avaje-inject to stay an optional dependency so that currently means that we can not use ServiceLoader with module-path due to https://bugs.openjdk.org/browse/JDK-8299504
=> Use alternative to ServiceLoader to load Plugin and PropertyRequiresPlugin

inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
Reverts avaje/avaje-inject#338 if we decide on the cyclical solution.
=> Go back to regular ServiceLoader

inject/src/main/java/io/avaje/inject/aop/FallbackFinder.java, inject/src/main/java/io/avaje/inject/aop/Invocation.java, inject/src/test/java/io/avaje/inject/aop/InvocationCallTest.java, inject/src/test/java/io/avaje/inject/aop/InvocationFallbackRawTest.java, inject/src/test/java/io/avaje/inject/aop/InvocationFallbackTest.java, inject/src/test/java/io/avaje/inject/aop/InvocationRunTest.java
I think Base is a better name, its a base abstract type for both Invocation.Call and Invocation.Run
=> Refactor rename Invocation.Build -> Invocation.Base

inject/src/main/java/io/avaje/inject/aop/Invocation.java
for my aspects it's kinda annoying to deal with checked exceptions. 
```
SVUtil.createScopedMDC(
mdc,
() -> {
try {
return invoke.invoke();
} catch (final Throwable e) {
if (e instanceof final RuntimeException ex) throw ex;
throw new InvocationException(e);
}
});
```
Sure would be nice to have a method I could call when I know my aspect isn't dealing with checked exceptions.
=> Add Invocation.invokeUnchecked() ... for ease of use when aspect isn't dealing wth checked exceptions

blackbox-test-inject/src/main/java/org/example/myapp/r4j/MyExample.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
Currently, proxying a method that `throws Throwable` causes a compilation error.
- if thrown types are unchecked, don't write a superfluous catch clause
- if method throws Throwable, rethrow it.
=> Fix Throwable Aspects

inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java
It seems some people try to use various bean methods to provide necessary beans. This helps make it clear that a `@Nullable` annotation or `@InjectModule` `requires` is needed to avoid compilation errors
=> Update javadoc for BeanScope Builder bean methods

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java
On the discord, an issue was reported that something like this generates invalid adapters.
```
@Singleton
public class ServersService {
...
public @Inject ServersService(final @NotNull JedisPool jedisPool, final @NotNull NatsConnection natsConnection) {
this.jedisPool = jedisPool;
this.natsConnection = natsConnection;
}
...
```
the generated DI class has annotations in the imports causing compilation to fail.
I could not replicate the issue on my local, but I'm sure this'll fix it. (or else do absolutely nothing).
=> Sanitize DI class imports

inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
Got a request saying
>I have a constructor injecting a MongoCollection<Document> param and the module has a requires for org.MongoDB.client.MongoCollection<org.Bson.Document>.class but it should be ignoring generics
that didn’t happen in earlier versions, haven’t narrowed it down to which inject version breaks it though
didn't get more than that but I think this should resolve it.
=> Fix Generic type Params showing up in generated requires

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/InjectProcessorTest.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/TestClass.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/Timed.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/TimedAspect.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/imported/ImportedClass.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/imported/ImportedClassProxy.java
Before Imported beans would have the DI/Proxy classes generated in the same package as the target type, causing runtime errors on Jlink application images.
- Modifies Generation to add `di` to the end of imported packages
- adds Inject Generator tests (we have a bunch of black-box tests, but it's easier to debug compilation when you can set breakpoints)
=> Fix split packages from Component.Import

inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java
Creates some default implementations returning the opposite of contains and equalTo for their opposing redundant methods.
I don't know why these are here, and perhaps they don't serve a purpose and their usages can be migrated to, well, the opposite of contains and equalTo.
=> Default implementations for redundant PropertyRequiresPlugin methods

inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/MethodTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/Param.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/TypeUse.java
It seems that our trim functions were not designed to handle type_use.
Use regex to trim annotations.
Use regex to sanitize imports.
=> Fix typeuse annotations not getting trimmed properly

inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject/src/main/java/io/avaje/inject/spi/DependencyMeta.java
Before:
```java
@DependencyMeta(type="io.helidon.nima.webserver.WebServer", method="com.jojo.helidon.api.config.ServerFactory$DI.build_server", dependsOn={"com.jojo.helidon.api.config.ServerFactory","io.helidon.nima.webserver.http.HttpService"}, autoProvides="io.helidon.nima.webserver.WebServer")
private void build_webserver_WebServer() {
ServerFactory$DI.build_server(builder);
}
```
After:
```java
@DependencyMeta(
type = "io.helidon.nima.webserver.WebServer",
method = "com.jojo.helidon.api.config.ServerFactory$DI.build_server",
dependsOn = {
"com.jojo.helidon.api.config.ServerFactory",
"io.helidon.nima.webserver.http.HttpService"
},
autoProvides = "io.helidon.nima.webserver.WebServer")
private void build_webserver_WebServer() {
ServerFactory$DI.build_server(builder);
}
```
Also makes the …
=> Make Generated `@DependencyMeta` annotations more readable

README.md, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject/src/main/java/io/avaje/inject/spi/Module.java
Before:
```
private final Class<?>[] autoProvides =
new Class<?>[] {
com.jojo.helidon.api.client.ApiClient.class,
com.jojo.helidon.api.service.ServiceClass.class,
io.avaje.http.client.HttpClient.class,
io.helidon.nima.webserver.WebServer.class,
io.helidon.nima.webserver.http.HttpService.class,
};
```
After:
```
private final Class<?>[] autoProvides = {
com.jojo.helidon.api.client.ApiClient.class,
com.jojo.helidon.api.service.ServiceClass.class,
io.avaje.http.client.HttpClient.class,
io.helidon.nima.webserver.WebServer.class,
io.helidon.nima.webserver.http.HttpService.class,
};
```
Also fixes a weird situation with Intellij where Aspects.Import doesn't exist on the cp.
In addition, adds Generated code to README.
=> Remove Generated Array Instantiation

inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
This prevents a situation where two maven projects A & B import the same class, and B depends on A, causing the same class to be wired twice and fail.
=> Prevent @Component.Import when type is already provided by external module

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-gradle-plugin/build.gradle, inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java, inject-maven-plugin/pom.xml, inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/spi/GenericType.java, inject/src/main/java/io/avaje/inject/spi/Plugin.java
Now Plugins can provide Aspect Provider classes. 
Works on my local, it fails on the pipeline since the inject plugins don't have the new version
- modify plugin interfaces to provide aspects as well
- modify inject plugins to use this new method
- enhance generator logging to show the detected modules
- now will log modules with INFO instead of DEBUG if `printModules` property is set (I really don't want to have to pull in an logging adapter just to set the log level for debugging)
=> Plugin Aspects

inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
Improve consistency and remove use of varargs. This is breaking API change for plugins using 9.3 (currently limited to avaje plugins?)
=> BeanScopeBuilder - change addPostConstruct() and addPreDestroy() methods

blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java, inject-test/src/main/java/io/avaje/inject/test/MetaInfo.java, inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DConfigProps.java, inject/src/main/java/io/avaje/inject/DSystemProps.java, inject/src/main/java/io/avaje/inject/spi/Builder.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java, inject/src/main/java/io/avaje/inject/spi/DBuilderExtn.java, inject/src/main/java/io/avaje/inject/spi/PropertyRequiresPlugin.java
- Explicit profiles via BeanScopeBuilder.profiles()
- Side effect free for InjectTest profiles
- Remove PropertyRequiresPlugin set property
=> BeanScopeBuilder.profiles() for explicit profiles

inject-generator/src/main/java/io/avaje/inject/generator/AllScopes.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject-test/src/test/java/org/example/custom4/GeneralScopeFactory.java, inject/src/main/java/io/avaje/inject/spi/DependencyMeta.java
For partial compile the meta data needs to be read from the @DependencyMeta to restore the state and for imported components we need to identify these as there $DI code is generated into a .di package to avoid split package issues with Java modules.
This change uses the explicit @DependencyMeta importedComponent property to identify those imported types (when a partial compile does not include them).
=> Fix for @Component.Import for partial compile - Add @DependencyMeta importedComponent property

inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java
In the tests this dependency is org.example.myapp.config.SomeOptionalDep. It gets added to autoRequires and in a full compile. For a partial compile this isn't restored from metadata and partial compile fails complaining that the dependency is not provided.
This fix is to mark this dependency as a soft: dependency. Partial compile reads the soft: dependency from metadata.
An alternative would be to add a mechanism (extra metadata annotation to save and restore the autoRequires types.
=> Fix for partial compile failing for external optional Dependency

blackbox-test-inject/src/main/java/org/example/myapp/config/A0.java, blackbox-test-inject/src/main/java/org/example/myapp/config/A1.java, blackbox-test-inject/src/main/java/org/example/myapp/config/AFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/config/BuilderFactory.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
When there are multiple Builders like A0.Builder and A1.Builder then we really need to use the full type name.
This change is to use the full type name when the short name matches Builder or Generated.
=> Fix for Factory with multiple "Builder" types - short names all exactly match Builder

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java, inject-generator/src/main/java/io/avaje/inject/generator/ImportTypeMap.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/A0.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/generic/MyConsumer.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/generic/MyConsumerFactory.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/nested/A0.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/nested/A1.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/nested/AFactory.java
Now generated `$DI` classes will use the more readable short name instead of the painfully long fully qualified names.
- Nested type instances will generate with enclosing type (`A.B value` instead of `some.package.A.B value`)
- Generated `_TYPE` variables will attempt to use short names if possible, but will revert to FQN when there are conflicts.
=> Use Short Name for Nested Types

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
Now people will know the exact class where they messed up. (this is pretty low priority)
=> Use LogError for Prototype Lifecycle Errors

blackbox-aspect/src/main/java/module-info.java, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject-generator/src/main/resources/META-INF/services/javax.annotation.processing.Processor
Now we can ensure module-info classes have the `provides` statement for the generated module classes.
Got around the `ModuleElement` limitations by using `Filer` to manually read the `module-info.java` file.
Fixes #389
=> Module Validation

blackbox-aspect/src/main/java/module-info.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
=> Use `Elements` to find `ModuleElement`

blackbox-other/src/main/java/org/other/one/OtherComponent.java, blackbox-other/src/main/java/org/other/one/OtherComponent2.java, blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java, inject-generator/src/main/java/io/avaje/inject/generator/ImportTypeMap.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject/src/main/java/io/avaje/inject/Component.java
For classpath-only applications, split packages are less of an issue.
Now can do this
```
@Component.Import(value = OtherComponent2.class, packagePrivate = true)
```
to make the generated DI classes for `OtherComponent2` reside in the same package.
fixes #396
=> Support @Import Package-Private Constructors 

blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java, blackbox-test-inject/src/main/java/org/example/myapp/Main.java, blackbox-test-inject/src/main/java/org/example/myapp/other/SimulateExternal.java, blackbox-test-inject/src/main/java/org/example/myapp/other/SimulateExternal2.java, blackbox-test-inject/src/main/java/org/example/myapp/other/SimulateExternalPub.java, blackbox-test-inject/src/main/java/org/example/myapp/other/SimulateExternalPub2.java, blackbox-test-inject/src/test/java/org/example/myapp/other/SimulateExternalTest.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Processor.java, inject/src/main/java/io/avaje/inject/Component.java
So the DI class to wire the imported component will be in the same package as the component unless it has a public constructor, and then it can be put into a
di subpackage.
=> With Component.Import check for public constructor

inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
due to the module validation, it's impossible to forget to add the required `provides` in a module-info.
=> Change no modules found message

blackbox-test-inject/src/main/java/org/example/myapp/ExampleService.java, blackbox-test-inject/src/main/java/org/example/myapp/HelloData.java, blackbox-test-inject/src/main/java/org/example/myapp/HelloService.java, blackbox-test-inject/src/main/java/org/example/myapp/MyDestroyOrder.java, blackbox-test-inject/src/main/java/org/example/myapp/config/AppConfig.java, blackbox-test-inject/src/main/java/org/example/myapp/i347/MyMetaDataRepo.java, blackbox-test-inject/src/main/java/org/example/myapp/named/MyNamed.java, blackbox-test-inject/src/test/java/org/example/myapp/MyDestroyOrderTest.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject/src/main/java/io/avaje/inject/Bean.java, inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/PreDestroy.java, inject/src/main/java/io/avaje/inject/spi/Builder.java, inject/src/main/java/io/avaje/inject/spi/ClosePair.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java
This allows control of the ordering of the PreDestroy methods. It does this using a int priority value. The default/baseline value is 1000. Setting values less than that means those methods run earlier and values over than means those methods run later.
e.g. using `io.avaje.inject.PreDestroy` `priority` attribute:
```java
// Run before all the normal pre-destroy methods
@PreDestroy(priority = 100)
void close() {... }
// Run after all the normal pre-destroy methods
@PreDestroy(priority = 2000)
void close() {... }
```
e.g. using `@Factory @Bean` ... added the `destroyPriority` attribute. 
```java
@Factory
class MyFactory {
@Bean(destroyMethod = "shutdown", destroyPriority = 1500)
Hello data() {
...
}
}
```
=> Add support for PreDestroy priority to control ordering

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/test/java/io/avaje/inject/generator/InjectProcessorTest.java
Since we know the FQNs of the Avaje library Plugins we can check for their presence at compile time. 
This means we don't need to use the inject-maven-plugin when using only avaje library plugins on the module path.
=> Auto Detect Avaje Library Plugins

.github/dependabot.yml, .github/workflows/dependabot-merge.yml, pom.xml
Adds dependabot to manage everything except the jakarta inject dependencies (since we like to change from jarkata to javax at will)
I've disabled auto-merge until the build checks are set as required
=> Add Dependabot

.github/workflows/dependabot-merge.yml
Requires branch protections have the build status checks
=> Enable dependabot auto-merge

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/MethodTestConditional.java, inject/src/main/java/io/avaje/inject/spi/Proxy.java
- adds a new member to the `@Proxy` annotation to track the typemirror across rounds
- will now read the proxy annotation values and read the bean conditions 
fixes #432
=> Fix Conditional Beans not working with AOP

blackbox-test-inject/src/main/java/org/example/myapp/config/AFactory.java, inject-generator/src/main/java/io/avaje/inject/generator/Append.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-test/src/test/java/org/example/autonamed/MyAutoB2OneImplied.java, inject-test/src/test/java/org/example/coffee/fruit/AppleService.java
Adds a try catch block to the generated code
=> #439 Handle case where Factory method throws exception

inject-generator/src/main/java/io/avaje/inject/generator/RequestScope.java, inject-test/pom.xml, inject-test/src/test/java/io/helidon/webserver/http/ServerRequest.java, inject-test/src/test/java/io/helidon/webserver/http/ServerResponse.java, inject-test/src/test/java/org/example/request/BController.java, inject-test/src/test/java/org/example/request/BControllerReqOnly.java, inject-test/src/test/java/org/example/request/BControllerResOnly.java, inject-test/src/test/java/org/example/request/BWebRoute.java, inject-test/src/test/java/org/example/request/BWebRouteTest.java, inject-test/src/test/java/org/example/request/CController.java
Simulate Helidon request response without requiring Java 21+
=> Support RequestScope with Helidon 4.0.0 (Nima)

blackbox-test-inject/src/main/java/org/example/myapp/generic/Generic.java, blackbox-test-inject/src/main/java/org/example/myapp/generic/GenericFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/generic/GenericFactoryTest.java, inject-test/pom.xml, inject-test/src/main/java/io/avaje/inject/test/MetaReader.java, inject-test/src/main/java/io/avaje/inject/test/Plugin.java, inject-test/src/test/java/io/avaje/inject/test/MetaReaderTest.java, inject-test/src/test/java/org/example/coffee/provider/BProvProviderTest.java, inject-test/src/test/java/org/example/generic/MzCrudServiceTest.java, inject-test/src/test/java/org/example/generic/PathBuildTaskTest.java, inject/src/main/java/io/avaje/inject/BeanScope.java, inject/src/main/java/io/avaje/inject/BeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/spi/EnrichBean.java, inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java, inject/src/main/java/io/avaje/inject/spi/SuppliedBean.java, inject/src/main/java/io/avaje/inject/spi/Types.java
- Fix situations where generic types were not being properly injected into certain types of test
- Adds new default methods to make retrieving a generic bean more intuitive
resolves #461
=> Fix Generic Junit Injection

inject/src/main/java/io/avaje/inject/spi/RawType.java, inject/src/main/java/io/avaje/inject/spi/SuppliedBean.java
As it is only used by SuppliedBean to obtain the
raw type from generic Type. If we expose the other methods like newParameterizedType() then that would go into a new public Types class.
=> Refactor rename Types -> RawType and make internal

README.md, blackbox-test-inject/src/main/java/org/example/myapp/r4j/MyExample.java, blackbox-test-inject/src/main/java/org/example/myapp/resilience4j/MyRetry.java, blackbox-test-inject/src/main/java/org/example/myapp/resilience4j/RetryProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/MethodTest.java, inject/src/main/java/io/avaje/inject/Component.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java, inject/src/main/java/io/avaje/inject/aop/AOPFallback.java, inject/src/main/java/io/avaje/inject/aop/Aspect.java, inject/src/main/java/io/avaje/inject/aop/Fallback.java, inject/src/main/java/io/avaje/inject/aop/FallbackFinder.java, inject/src/main/java/io/avaje/inject/aop/Invocation.java, inject/src/main/java/io/avaje/inject/aop/InvocationException.java, inject/src/test/java/io/avaje/inject/aop/InvocationFallbackTest.java
The current way of using fallback methods is pretty obtuse, so this adds
- Adds a new annotation to mark a method as a fallback for AOP.
- will generate code to register a fallback method to an invocation
- Adds new method to `Invocation` to invoke a registered fallback method
- also will use method references in generated proxies if possible
Given stuff like this:
```java
@MyRetry
public String retry2(String param0, int param1) {
retryWithFallbackCounter++;
throw new IllegalArgumentException("Retry2Fail[" + param0 + "," + param1 + "]");
}
@AOPFallback("retry2")
public String fallbackRetry2(String param0, int param1, Throwable e) {
return "fallbackRetry2-" + param0 + ":" + param1 + ":" + e.getMessage();
}
```
this will get generated
```java
@Override
public java.lang.String retry2(String …
```
=> Use CodeGen for AOP Fallback

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java, inject/src/main/java/io/avaje/inject/spi/Proxy.java
There's no need for the proxy annotation to have an attribute, when we can simply check the superclass
=> Simplify Proxy Generation

inject-test/src/main/java/io/avaje/inject/test/GlobalTestScope.java, inject-test/src/main/java/io/avaje/inject/test/MetaReader.java, inject-test/src/main/java/io/avaje/inject/test/SetupMethods.java, inject-test/src/test/java/org/example/inherit/MyOneAbstract.java, inject-test/src/test/java/org/example/inherit/MyOneTest.java
With a test class with inheritance and field injection on inherited fields, those fields were not being injected.
This fixes this issue.
=> Fix for @InjectTest with inherited field injection

inject-test/src/test/java/org/example/coffee/BeanScopeBuilderAddTest.java, inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithNamedTest.java, inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
Prior to this fix if the parent returning an empty map it was unmodifiable and resulted in an error.
=> Fix when getting map of beans with parent scope

inject-test/src/main/java/io/avaje/inject/test/GlobalInitialise.java, inject-test/src/main/java/io/avaje/inject/test/GlobalTestBeans.java, inject-test/src/main/java/io/avaje/inject/test/InjectExtension.java, inject-test/src/main/java/io/avaje/inject/test/MetaInfo.java, inject-test/src/main/java/io/avaje/inject/test/MetaReader.java, inject-test/src/main/java/io/avaje/inject/test/PluginMgr.java, inject-test/src/main/java/io/avaje/inject/test/TestBeanScope.java, inject-test/src/main/java/io/avaje/inject/test/TestBeans.java, inject-test/src/test/java/io/avaje/inject/test/MetaReaderTest.java
- Rename GlobalTestScope -> GlobalTestBeans
- Lift and rename GlobalTestScope.Pair to TestBeans
- The plugin scope lives in TestBeans and scoped with the associated test bean scope (created together, closed together)
- Rename PluginInitialise to PluginMgr
- Rename TSBuild to GlobalInitialise
Note the plugin for avaje-nima creates the nima http server, so now this will be started and stopped with the associated bean scope.
=> Follow up to #503 for Plugin scope to match the test bean scope

README.md
- Adds javadoc badge 
- adds Dagger to the DI comparison table
=> Update README table

inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/provider/FactoryProvider.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/provider/Grinder.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/provider/ProviderUser.java, inject-test/src/test/java/org/example/coffee/provider/FactoryProvider.java, inject-test/src/test/java/org/example/coffee/provider/FactoryProviderTest.java
- Fixes generated Modules not compiling in certain cases when using `Provider` in factory classes
- Fixes DI classes not compiling with Providers of Generic Types
- remove duplicate auto-provides in dependency metadata
=> Fix Factory Providers

blackbox-test-inject/src/main/java/org/example/myapp/supplier/MySupConsumer.java, blackbox-test-inject/src/main/java/org/example/myapp/supplier/MySupFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/supplier/MySupFactoryTest.java
Note that with `Supplier<T>` its a little different than `Provider<T>` in that `Provider<T>` is used to support circular dependency wiring so its a way to delay the wiring (until after all the constructors are called).
We don't have that limitation with Supplier.
=> Add a test that uses `Supplier<T> wrt #519

inject/src/main/java/io/avaje/inject/spi/ProviderPromise.java
=> Better error when calling Provider.get() too early (during DI wiring)

README.md, inject/README.md
=> README typo fixes

blackbox-test-inject/src/main/java/org/example/myapp/config/AppConfig.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyFactory.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
Hello, everyone! Thank you all for your work.
Avaje-Inject currently generates invalid code when a "provider" method (i.e. `@Prototype`, `@Lazy`, etc.) has a `throws` clause.
There are two problems:
1. a syntax error: `try { ... } } catch`.
2. the lambdas passed to `Builder::register(Lazy|Provider)` do not handle the declared `Throwable`s.
This fixes those problems by wrapping the _bodies_ of the lambdas passed to `Builder::register(Lazy|Provider)` in `try` blocks.
To demonstrate, here are the (relevant) differences in the generated code before and after applying the fix:
```diff
--- before-fix-fallible-providers/blackbox-test-inject/target/generated-sources/annotations/org/example/myapp/config/AppConfig$DI.java
+++ fix-fallible-providers/blackbox-test-inject/target/generated-sources/annot …
```
=> fix: compilation error with providers and `throws`

inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-test/src/test/java/org/example/coffee/provider/FactoryProvider.java, inject-test/src/test/java/org/example/coffee/provider/FactoryProviderTest.java, inject-test/src/test/java/org/example/coffee/provider/ProtoTypeNumberGetter.java
Extracted this fix from #540
@Prototype with Provider<T> currently produces code that registers Provider<Provider<T>> instead of Provider<T> and this fixes that.
=> Fix support for @Prototype with Provider<T>

inject-test/src/test/java/org/example/coffee/qualifier/MegaStoreManager.java, inject-test/src/test/java/org/example/coffee/qualifier/MetaStoreManagerTest.java, inject-test/src/test/java/org/example/coffee/qualifier/NoNameStore.java, inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithNamedTest.java, inject/src/main/java/io/avaje/inject/spi/DContextEntry.java
In the case where we have 2 beans of the same type and one has no qualifier, then when injecting a bean with no qualifier specified then prefer to wire the bean with no qualifier.
Example: In the MegaStoreManager example we have NoNameStore as a bean with no name qualifier and that is preferred for the noQualifier injection point.
=> #555 No qualifier injection point prefers no qualifier bean (over named bean)

inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java
I don't why we have the .filter() and ::cast for the service loading here, seems unnecessary and can simplify.
=> maven plugin: #567 Followup, Simplify ServiceLoader of InjectPlugin

inject/src/main/java/io/avaje/inject/spi/Module.java
Restore the Module interface to use Class<?> as per 9.x The AvajeModule interface changes this to Type
=> #567 Backwards Compatible Generic Modules, restore Module interface

inject-generator/src/main/java/io/avaje/inject/generator/Constants.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
The change to autoProvides for Event support also meant that http controllers and http routes started to get included into autoProvides. The problem there is that http controllers are not expected to be public exported types and autoProvides with GenericType doesn't check is the type parameters are public.
=> Restore autoProvides to exclude http controllers and generated http routes

blackbox-test-inject/src/main/java/org/example/myapp/other/ConfigFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/other/ConfigFactoryTest.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java
As currently the full generic type is not used in the generated build method name but just the top level main type then the generated build method can clash resulting in a compile error.
This fix detects this case and includes the factory method name in the "generated build method" such that it avoids the clash.
=> Fix for unnamed generic types returned by @Factory @Bean

README.md
Update readme to provide doc for new `InjectSPI` interface
Also see https://github.com/avaje/website-source/pull/57
=> Update README to provide doc for InjectSPI

.github/workflows/build.yml, .github/workflows/jdk-ea.yml
I mean it would be great to have immediate feedback when a PR will break on the latest JDK instead of waiting for a time later in the week
=> Add GA/EA JDK to PR builds

blackbox-aspect/pom.xml, blackbox-other/pom.xml, blackbox-test-inject/pom.xml, inject-aop/pom.xml, inject-events/pom.xml, inject-events/src/main/java/module-info.java, inject-generator/pom.xml, inject-gradle-plugin/build.gradle, inject-maven-plugin/pom.xml, inject-test/pom.xml, inject/pom.xml, pom.xml
=> Remove `InjectSPI` from events

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/test/java/io/avaje/inject/generator/InjectProcessorTest.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java
Now relies on spi-service to write spis
relies on https://github.com/avaje/avaje-spi-service/pull/25
---
Note: This ultimately is required because with the change to a common service interface of InjectExtension we now more likely get multiple services registering for the same InjectExtension api interface - so those need to be merged into the same META-INF/services file via avaje-spi-service.
=> Write SPIs to META-INF/generated-services so that they can be merged later via avaje-spi-service

inject/src/main/java/io/avaje/inject/AssistFactory.java, inject/src/main/java/io/avaje/inject/Bean.java, inject/src/main/java/io/avaje/inject/Component.java, inject/src/main/java/io/avaje/inject/External.java, inject/src/main/java/io/avaje/inject/Factory.java, inject/src/main/java/io/avaje/inject/InjectModule.java, inject/src/main/java/io/avaje/inject/PostConstruct.java, inject/src/main/java/io/avaje/inject/PreDestroy.java, inject/src/main/java/io/avaje/inject/Primary.java, inject/src/main/java/io/avaje/inject/Profile.java, inject/src/main/java/io/avaje/inject/Prototype.java, inject/src/main/java/io/avaje/inject/QualifiedMap.java, inject/src/main/java/io/avaje/inject/RequiresBean.java, inject/src/main/java/io/avaje/inject/RequiresProperty.java, inject/src/main/java/io/avaje/inject/Secondary.java, inject/src/main/java/io/avaje/inject/spi/Proxy.java
Change annotations to have Class retention with the exception of:
- `@Component`
- `@PreDestroy`
- `@PostConstruct`
The reason for these exceptions is that for APM (Application Performance Monitoring) tools like `avaje-metrics` detect and enhance with timing all public methods of all `@Component` / `@Singleton`.  Lifecycle methods annotated with `@PreDestroy`/ `@PostConstruct` typically get excluded by default from APM so we need to detect those as well.
Note that if projects need some of these annotations to have RUNTIME or CLASS retention then please log an issue with the use case that you need to support - thanks.
=> Make Annotations Source Retention

.github/workflows/build.yml, blackbox-aspect/pom.xml, blackbox-other/pom.xml, blackbox-test-inject/pom.xml, inject-aop/pom.xml, inject-events/pom.xml, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/ModuleData.java, inject-gradle-plugin/build.gradle, inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java, inject-maven-plugin/pom.xml, inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java, inject-test/pom.xml, inject/pom.xml, jakarta-to-javax.sh, javax-to-jakarta.sh, pom.xml
Fixes situations where compilation fails with `Fatal error compiling: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1` 
- Now will not fail compilation if unable to parse the `avaje-module-dependencies.csv` file 
- remove extra newline and copied text from generated csv
- fix javax workflow to include the inject plugin
=> Fix Inject Plugin CSV Generation/Parsing

inject-events/src/main/java/io/avaje/inject/events/Event.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/LoadServices.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java, inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java, inject-test/src/main/java/io/avaje/inject/test/PluginMgr.java, inject/src/main/java/io/avaje/inject/spi/DBeanScope.java, inject/src/main/java/io/avaje/inject/spi/DContextEntry.java
Fixes findings from sonar.
- reducing cognitive complexity
- removing unused imports
- rename some variables
=> Sonar Fixes

inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
10.0-RC5 introduced a regression that stops "Partial Compilation" from working. This is due to the ProcessingContext.isInjectModule() not correctly detecting the current module. This meant no existing module was found, no dependency meta data for the module was read, a new module is created for the components included in the partial compile and generally that will fail with missing dependencies.
A workaround is to perform a full compile (but this isn't really a workable solution - its important that partial compile works).
=> Fix partial compile regression introduced in 10.0-RC5

inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
Fixes a regression that breaks partial compilation when qualifiers are used.
Regression introduced in 10.1 via:
https://github.com/avaje/avaje-inject/pull/645/files
With this regression we observe compile errors stating that dependencies with qualifiers are missing. When reviewing the relevant generated @metadata dependsOn attributes in the generate source we see that there are qualifiers incorrectly appended to the factory type.
The fix is in the MetaData constructor, such that the dependsOn does NOT use the name/qualifier of the type.
=> Fix partial compile regression introduced in 10.1 via #645

inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
I have only observed this NPE on partial compilation errors. This might not be strictly required but putting this fix in for that odd case.
=> Fix NPE on module.name()

inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
Can't seem to replicate the issue in a test, but when I install into my local maven repo it resolves the avaje-http build issue.
=> Fix cases where test beans fail module validation

inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleAssistWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleOrderWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java
Was testing with valhalla, and thought why not?
- will generate value classes if on a valhalla JDK build and previews are enabled
- Modifies generated module classes to work as value types (no mutable fields)
```java
@Generated
@InjectModule
public final value class ApiModule implements AvajeModule {
@Override
public void build(Builder builder) {
// builder is now passed into the DI methods instead of being a field
build_config_HttpClientFactory(builder);
}
...
```
=> Generate Value Classes When on Valhalla

.github/dependabot.yml
Now dependabot should create a single PR for all the dependencies. [Example PR](https://github.com/SentryMan/avaje-javalin-api-example/pull/50)
=> Update dependabot to actually group dependency updates

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
Since we don't create `avaje-module-provides.txt` anymore, detection should be based on the generated `avaje-module-dependencies.csv` provided by the plugins
=> Fix ExternalProvider warning message

inject/src/main/java/module-info.java
I ran into some jlink trouble.
This changes `jakarta.inject` from being `static`/optional to being a required module dependency in module-info.
=> Make Jakarta Inject required in module-info

blackbox-test-inject/src/main/java/org/example/myapp/beantypes/AbstractSuperClass.java, blackbox-test-inject/src/main/java/org/example/myapp/beantypes/BeanTypeComponent.java, blackbox-test-inject/src/main/java/org/example/myapp/beantypes/LimitedFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/beantypes/LimitedInterface.java, blackbox-test-inject/src/test/java/org/example/myapp/beantypes/BeanTypeComponentTest.java, inject-generator/src/main/java/io/avaje/inject/generator/AssistBeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/LimitedFactory.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/LimitedOtherComponent.java, inject/src/main/java/io/avaje/inject/BeanTypes.java
- Creates `@BeanTypes` annotation to define the injectable types associated with a bean. 
- the values provided to the annotation will also override auto-provides generation
Given the class:
```java
@Component
@BeanTypes(SomeInterface2.class)
public class LimitedOtherComponent extends AbstractSuperClass
implements SomeInterface, SomeInterface2 {}
```
the following will be generated: 
```java
public final class LimitedOtherComponent$DI  {
/**
* Create and register LimitedOtherComponent.
*/
public static void build(Builder builder) {
if (builder.isAddBeanFor(SomeInterface2.class)) {
var bean = new LimitedOtherComponent();
builder.register(bean);
}
}
}
```
=> Add `@BeanTypes` Annotation to Limit Injection Types

blackbox-test-inject/pom.xml, inject-generator/pom.xml, inject-test/pom.xml, inject/pom.xml, pom.xml
The updated parent pom allows overriding argLine via properties section. We desire this to tidy things up and make it easier to support a EA Valhalla build.
=> Update parent pom, tidy use argLine in properties

inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
=> Log Error on Empty Scope instead of Failing

inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject/src/main/java/io/avaje/inject/spi/DBeanMap.java, inject/src/main/java/io/avaje/inject/spi/DBeanScopeProxy.java
- Use a common function for proxy scope errors
- remove comments from generated bean DI classes
helps resolve #695
=> Tidy Internals

inject-events/src/main/resources/META-INF/services/io.avaje.inject.spi.InjectExtension, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
Generate Meta-INF/services entry for `inject-events` at compile time.
resolves #703 #702 #700 
relies on https://github.com/avaje/avaje-spi-service/pull/34
=> Generate Meta-INF/services entry for `inject-events`

inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-test/src/test/resources/META-INF/services/io.avaje.inject.spi.InjectExtension
Currently, when inject-test is built, it has a `META-INF/services/InjectExtension` with an entry for `io.avaje.inject.events.spi.ObserverManagerPlugin`. 
This means that it has hard dependency on inject-events. When events is not present this exception occurs:
```
java.util.ServiceConfigurationError: ServiceConfiguration io.avaje.inject.spi.InjectExtension: Provider io.avaje.inject.events.spi.ObserverManagerPlugin not found
```
this pr makes it so that entry is not added to inject-test
=> Fix Inject-test such that it does NOT have a dependency on inject-events

inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
Currently, the processor adds the supertypes of `java.lang` classes as keys for wiring. When beans are supplied manually this can cause issues.
Given:
```java
public enum State {
ON, OFF
}
@Factory
public class Configuration {
@Bean
public State state() {
return State.ON;
}
}
```
Before: 
```java
public static void build_state(Builder builder) {
if (builder.isAddBeanFor(State.class, TYPE_EnumState, Constable.class, Comparable.class, Serializable.class)) {
var factory = builder.get(Configuration.class);
var bean = factory.state();
builder.register(bean);
}
}
```
After: 
```java
public static void build_state(Builder builder) {
if (builder.isAddBeanFor(State.class)) {
var factory = builder.get(Configuration.class);
var bean = factory.state();
builder.register(bean);
}
}
```
Fixes #710
=> Cease reading supertypes for `java.lang`

inject-generator/pom.xml, inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java
Currently, the inject-gradle-plugin's outputs are not detected by the processor. 
- gradle plugin now runs before build instead of after clean
Depends on https://github.com/avaje/avaje-prisms/pull/86
=> Fix Gradle Build Folder Detection

inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java
We have no mutable state that is shared across different instances.
Resolves this warning for parallel builds.
```
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked as thread-safe in blackbox-test-inject:
[WARNING]   io.avaje:avaje-inject-maven-plugin:10.5-RC3
[WARNING]
[WARNING] Enable debug to see precisely which goals are not marked as thread-safe.
[WARNING] *****************************************************************
```
=> Mark maven plugin goal as thread safe

blackbox-aspect/src/main/java/module-info.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
Removes the main weakness of #718 by reading the `provides` directives of all external modules.
=> Remove `exports` limitation from Module Path Detection

inject-generator/pom.xml, inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java
- change gradle plugin to run before the `compileJava` task
- bump prisms version
Relies on https://github.com/avaje/avaje-prisms/pull/89
=> Fix Gradle Test Resource Detection

inject-generator/src/main/java/io/avaje/inject/generator/EventPublisherWriter.java
When the generator tries to create an `Event` implementation for a type that doesn't exist, it throws an unhelpful null pointer 
part of #689
=> Handle `EventPublishWriter` `TypeElement` nulls

blackbox-aspect/src/main/java/module-info.java, blackbox-aspect/src/main/java/org/example/external/aspect/PluginProvidedClass.java, blackbox-aspect/src/main/java/org/example/external/aspect/spi/AspectPlugin.java, blackbox-test-inject/src/test/java/org/example/myapp/other/WireOther.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-generator/src/main/java/module-info.java, inject/src/main/java/io/avaje/inject/spi/PluginProvides.java
- adds a `@PluginProvides` annotation that the processor can autodetect via `getAllModuleElements` (not sure I like the name though, feel free to change it if you got a better one)
- writes plugin/module text files for reuse during test compilation 
resolves #724
=> Add annotation for module-path `InjectPlugin` auto-detection

blackbox-aspect/src/main/java/org/example/external/aspect/spi/AspectPlugin.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject/src/main/java/io/avaje/inject/spi/PluginProvides.java
=> Rename `@PluginProvides` `provides` member to `value`

inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
I have trouble replicating, but if the module-info is misconfigured in a particular way `getEnclosedElements` throws a null pointer exception.
=> Fix odd null pointer in module detection

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java, inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java, inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
- Now will add all detected modules/plugins to `META-INF/services`
- add an option to disable just in case
- now maven/gradle plugin will output plugin information in a csv format
resolves #731 
relies on prisms 1.35
=> Merge Detected Services into `META-INF`

blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyBean.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyFactory.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/test/java/io/avaje/inject/generator/InjectProcessorTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyBean.java
Currently, this generates invalid code:
```java
@Singleton
public class LazyBean {
@Inject Provider<Integer> intProvider;
public LazyBean() throws Exception {}
}
```
Now properly generates code:
```java
public final class LazyBean$DI  {
public static void build(Builder builder) {
if (builder.isAddBeanFor(LazyBean.class)) {
builder.registerProvider(() -> {
try {
var bean = new LazyBean();
bean.intProvider = builder.getProvider(Integer.class);
return bean;
} catch (Throwable e) {
throw new RuntimeException("Error during wiring", e);
}
});
}
}
}
```
=> Fix Lazy Checked Exceptions

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/Constants.java, inject-generator/src/main/java/io/avaje/inject/generator/IncludeAnnotations.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/package-info.java, inject-generator/src/main/java/module-info.java, inject-generator/src/test/java/io/avaje/inject/generator/IncludeAnnotationsTest.java
We already know that they are autocloseable, must we really go through the ceremony of `@Bean(closeable=true)`?
- use http annotation prisms
- generated Avaje Http Client implementations are now registered as closeable if `HttpClient` is detected to be a subtype of AutoCloseable
=> Mark Generated Avaje HttpClient implementations as Closeable

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject/src/main/java/io/avaje/inject/spi/Builder.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java, inject/src/main/java/io/avaje/inject/spi/DBuilderExtn.java
I feel this rolls off the tongue a little better.
- deprecated the old methods for removal in 11
- change generation to use the new name
=> Rename `isAddBeanFor` to `isBeanAbsent`

inject-aop/src/main/java/io/avaje/inject/aop/Aspect.java
When using JDK 23+ module imports, the `List` type from `java.base`  and `io.avaje.inject.aop` have a name collision.
```java
import module java.base;
import module io.avaje.inject;
public class Example {
void main() {
List.of(); // this fails to resolve the import
}
}
```
=> Fix Repeatable Annotation Name Collision

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
Now separates the external spi from the generated classes
=> Fix Module Validation

blackbox-test-inject/src/main/java/org/example/myapp/MyNestedDestroy.java, blackbox-test-inject/src/main/java/org/example/myapp/config/AFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/HelloServiceTest.java, blackbox-test-inject/src/test/java/org/example/myapp/testconfig/CountTestScopeStart.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/test/java/io/avaje/inject/generator/MethodReaderTest.java
For example: `@Bean(destroyMethod = "reaper().stop()")`
=> #749 Add support for chained methods in @Bean(destroyMethod)

.gitignore, blackbox-other/src/main/java/org/other/one/OtherComponent3.java, blackbox-test-inject/src/main/java/org/example/myapp/ConfigPropertiesPlugin.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/imported/ImportedProtoType.java, inject/src/main/java/io/avaje/inject/Component.java
Adds an attribute to the `Component.Import` annotation to make imported types have the prototype/lazy scope
=> Now can import `Prototype`/`Lazy` Beans

blackbox-test-inject/src/main/java/org/example/myapp/config/LifeFour.java, blackbox-test-inject/src/main/java/org/example/myapp/config/LifeOne.java, blackbox-test-inject/src/main/java/org/example/myapp/config/LifeProtoTwo.java, blackbox-test-inject/src/main/java/org/example/myapp/config/LifeThree.java, blackbox-test-inject/src/main/java/org/example/myapp/config/LifeTwo.java, blackbox-test-inject/src/test/java/org/example/myapp/config/PostConstructParametersTest.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lifecycle/Minos.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lifecycle/Serpent.java
generates the lookup and fetches beans for `PostConstruct ` lifecycle methods. (Before we could only inject the `BeanScope`)
Given:
```java
@Singleton
public class Minos {
@PostConstruct
void prepareThyself(Serpent serpent, Consumer<String> c, BeanScope b) {}
}
```
the following is generated:
```java
public final class Minos$DI  {
public static final Type TYPE_ConsumerString =
new GenericType<Consumer<String>>(){}.type();
public static void build(Builder builder) {
if (builder.isBeanAbsent(Minos.class)) {
var bean = new Minos();
var $bean = builder.register(bean);
builder.addPostConstruct(b -> $bean.prepareThyself(b.get(Serpent.class,"!serpent"), b.get(TYPE_ConsumerString), b));
}
}
}
=> `PostConstruct` method Direct Injection

blackbox-test-inject/src/main/java/org/example/myapp/MyNestedDestroy.java, blackbox-test-inject/src/main/java/org/example/myapp/config/AFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/HelloServiceTest.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/DestroyMethods.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/test/java/io/avaje/inject/generator/MethodReaderTest.java
Example:
```java
@Factory
final class MyFactory {
@Bean
MyComponent myComponent() {
...
}
@PreDestroy(priority = 3000)
void destroyMyComponent(MyComponent bean) {
...
}
```
- ONLY valid on factory components
- An alternative to @Bean(destroyMethod)
- The @PreDestroy method matches to a @Bean by type only (ignores qualifiers, only 1 argument to the destroy method)
=> #749 Add support for a @PreDestroy method on a factory, alternative to @Bean(destroyMethod)

inject-test/src/main/java/io/avaje/inject/test/MetaReader.java, inject-test/src/test/java/org/example/coffee/list/ListInject.java
now can do
```java
@InjectTest
class ListInject {
@Inject List<Somei> testSomei;
@Test
void test() {
assertThat(testSomei).isNotEmpty();
}
}
```
=> [test] allow list injection for tests

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lifecycle/ClientFactory.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lifecycle/ClientInterface.java, inject-test/pom.xml, inject-test/src/test/java/org/example/coffee/factory/MyFactory.java, inject-test/src/test/java/org/example/coffee/factory/MyFactoryTest.java, inject-test/src/test/java/org/example/request/MyHttpClient.java
Fix issue where incorrect predestroy hooks were generated
=> Fix Avaje HttpClient interface generation error

inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
It's hard to replicate, but in certain situations it is possible to get an OOM error when compiling. I've been seeing it occasionally when I debug the generator with eclipse.
this change causes the qualifier suffix to be appended after annotation stripping
=> Fix `cutAnnotations` Edge Case

inject/src/main/java/io/avaje/inject/RequiresBean.java, inject/src/main/java/io/avaje/inject/RequiresProperty.java
=> Fix `@Requires` Retention

inject-generator/src/main/java/io/avaje/inject/generator/InjectTestProcessor.java, inject-generator/src/main/java/module-info.java, inject-test/pom.xml, inject-test/src/main/java/io/avaje/inject/test/LookupProvider.java, inject-test/src/main/java/io/avaje/inject/test/Lookups.java, inject-test/src/main/java/io/avaje/inject/test/MetaReader.java, inject-test/src/main/java/module-info.java, inject/pom.xml, pom.xml
Since mockito internals are now forbidden, generate a lookup class and use `VarHandle`s
- use `VarHandle` for getting/setting test fields
- adds a new processor to generate test lookups
- adds new SPI to inject test
=> [inject-test] Generate Method Handle Lookups

inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java
Saw some cases where users had multiple for whatever reason and it wasn't working right. (strict wiring was being overridden)
- validates that no extra `@InjectModule`s are lying around
- filter out generated classes from validation (we expect to read them)
- filter out custom scope annotations as well
=> Validate only a single `@InjectModule` annotation

inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java
APT Errors tend to spiral, this ensures that a user can more clearly identify generation errors
=> Cancel Generation on errors

inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
turns out getDirectives throws an NPE if it's an automatic module. Only happens with JDT though
=> Fix ExternalProvider on JDT

blackbox-test-inject/src/main/java/org/example/myapp/config/BFace.java, blackbox-test-inject/src/main/java/org/example/myapp/config/BFactory.java, blackbox-test-inject/src/test/java/org/example/myapp/config/BFactoryTest.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java
Given a `@Factory` with 2 or more bean methods that return the same type, and effectively clash on qualifier name (typically missing) then make this a compilation error.
The error suggests to add a `@Named` or qualifier annotation to resolve the issue.
Example:
```java
@Factory
class MyFactory {
@Bean
BFace one() {
...
}
@Bean
BFace two() {
...
}
```
=> Detect clash with multiple @Bean methods returning same type

.github/workflows/build.yml, inject-generator/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/RequestScope.java, inject-test/pom.xml, inject-test/src/test/java/org/example/custom/CustomScopeTest.java, inject-test/src/test/java/org/example/request/JexController.java, inject-test/src/test/java/org/example/request/JexControllerTest.java
=> Fix Jex Request-Scoped Context

inject-generator/pom.xml, inject-generator/src/main/java/module-info.java
They aren't required at runtime
=> [generator] Make aop/events `requires static`

blackbox-test-inject/src/main/java/org/example/myapp/duplicate/SameType.java, blackbox-test-inject/src/main/java/org/example/myapp/duplicate/two/SameType.java, blackbox-test-inject/src/test/java/org/example/myapp/duplicate/SameTypeTest.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/duplicate/SameType.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/duplicate/two/SameType.java
Now will fully qualify when a short name conflicts.
fixes #794
=> Fix duplicate short names in Module Generation

blackbox-multi-scope/pom.xml, blackbox-multi-scope/src/main/java/org/multi/crosscut/BeanCross.java, blackbox-multi-scope/src/main/java/org/multi/crosscut/BeanCross2.java, blackbox-multi-scope/src/main/java/org/multi/crosscut/BeanCross3.java, blackbox-multi-scope/src/main/java/org/multi/main/CrossCutMain.java, blackbox-multi-scope/src/main/java/org/multi/moda/BeanInModA.java, blackbox-multi-scope/src/main/java/org/multi/modb/BOther.java, blackbox-multi-scope/src/main/java/org/multi/modb/BeanInModB.java, blackbox-multi-scope/src/main/java/org/multi/modc/modb/BeanInModC.java, blackbox-multi-scope/src/main/java/org/multi/modc/modb/COther.java, blackbox-multi-scope/src/main/java/org/multi/scope/CrossCutScope.java, blackbox-multi-scope/src/main/java/org/multi/scope/ModAScope.java, blackbox-multi-scope/src/main/java/org/multi/scope/ModBScope.java, blackbox-multi-scope/src/main/java/org/multi/scope/ModCScope.java, blackbox-multi-scope/src/test/java/org/multi/crosscut/BeanCrossTest.java, blackbox-multi-scope/src/test/java/org/multi/main/CrossCutMainTest.java, pom.xml
This is for testing out the multi-scope cases in a separate test module.
The guts is that to build the scope we currently need to order the modules:
```java
public static BeanScope buildScope() {
return BeanScope.builder()
.modules(new ModAModule(), new ModCModule(), new ModBModule(),  new CrossCutModule())
.build();
}
```
- CrossCut requires ModA and ModB
- ModB requires ModC
The ordering of the modules should work off the `requires`.
=> Add test module blackbox-multi-scope

blackbox-test-inject/src/main/java/org/example/myapp/lifecycle/GreetingService.java, blackbox-test-inject/src/main/java/org/example/myapp/lifecycle/ServiceCreator.java, blackbox-test-inject/src/test/java/org/example/myapp/lifecycle/HelloServiceTest.java, blackbox-test-inject/src/test/java/org/example/myapp/lifecycle/TestBeanFactory.java, inject-generator/src/main/java/io/avaje/inject/generator/AnnotationUtil.java
=> Support Inherited Lifecycle on Factory Methods

inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-test/src/test/java/org/example/coffee/CoffeeMakerTest.java, inject-test/src/test/java/org/example/coffee/generic/MultiGenericConsumer.java, inject-test/src/test/java/org/example/coffee/generic/MultiGenericConsumerTest.java
- fix cases where a list of generic wildcards generates bad code
- now generic types are registered with their main type as a key
=> Support Nested Wildcard Lists

blackbox-test-inject/src/main/java/io/ebean/Database.java, blackbox-test-inject/src/main/java/io/ebean/MyDatabase.java, blackbox-test-inject/src/main/java/org/example/myapp/config/AppConfig.java, blackbox-test-inject/src/test/java/org/example/myapp/DefaultDestroyTest.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
For graceful shutdown, we desire components to shutdown in an appropriate order. For `io.ebean.Database` it should be shutdown last.
Adds a default shutdown method and shutdown priority for special components such that they default to doing "the right thing" wrt graceful shutdown.
For ebean:
```java
@Bean
Database database()
```
We desire that to effectively default to:
```java
@Bean(destroyMethod = "shutdown", destroyPriority = Integer.MAX_VALUE)
Database database()
```
... we want the generated code to have `addPreDestroy()` like:
```java
var bean = factory.database(builder.get(ConfigWrapper.class,"!config"));
var $bean = builder.register(bean);
builder.addPreDestroy($bean::shutdown, 2147483647);
```
=> Graceful shutdown - defaults for io.ebean.Database to shutdown() last

blackbox-test-inject/pom.xml, blackbox-test-inject/src/main/java/org/example/myapp/assist/droid/ACar.java, blackbox-test-inject/src/main/java/org/example/myapp/assist/droid/Car.java, blackbox-test-inject/src/main/java/org/example/myapp/config/SomeOptionalUser.java, blackbox-test-inject/src/main/java/org/example/myapp/config/SomeOptionalUser2.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyBean.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyFactory.java, inject-aop/pom.xml, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java, inject-maven-plugin/pom.xml, inject-test/pom.xml, inject/pom.xml
Fix issue where TYPE_USE annotations would cause the wrong type to be registered, causing errors like:
`No dependency provided for java.util.concurrent.atomic.@org.jspecify.annotations.Nullable AtomicBoolean on org.example.myapp.lazy.LazyBean`
=> Fix TYPE_USE annotated dependencies

inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/generic/GenericImpl.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/generic/GenericInterfaceObject.java
This PR fixes a bug in Util.shortName(...) where nested types like java.util.concurrent.Flow.Publisher were resolved incorrectly as Publisher, which caused generated code to fail compilation when the short name was not imported correctly.
=> fix: handle nested java types like Flow.Publisher in Util.shortName

blackbox-test-inject/src/main/java/org/example/myapp/config/MyAopProviderConsumer.java, blackbox-test-inject/src/test/java/org/example/myapp/config/MyAopProviderConsumerTest.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/aspect/MethodTest.java
In a case like 
```java
@Timed
@Component
public class MethodTest {
Provider<TestClass> provider;
public MethodTest(Provider<TestClass> provider) {
this.provider = provider;
}
//...
}
```
It was generating incorrectly and causing a compilation error 
```java
@Proxy
public final class MethodTest$Proxy extends MethodTest {
//...
public MethodTest$Proxy(AspectProvider<Timed> timed, TestClass provider) { //invalid
super(provider);
//....
}
}
=> Fix invalid `Provider` generation with AOP

inject-generator/src/main/java/io/avaje/inject/generator/ScopeUtil.java, inject-generator/src/test/java/io/avaje/inject/generator/ScopeUtilTest.java
now generated module classes will not have the name `AvajeModule` when the package is `avaje`, which clashes with the class of the same name
=> Support a main package called `avaje`

blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyBean.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyBeanAOP.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyFactory.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyImpl.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyInterface.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy/OldLazy.java, blackbox-test-inject/src/test/java/org/example/myapp/lazy/LazyTest.java, inject-generator/src/main/java/io/avaje/inject/generator/AspectMethod.java, inject-generator/src/main/java/io/avaje/inject/generator/AssistBeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanLazyWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanProxyWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyBeanAOP.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyBeanTypes.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyFactory.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyInterface.java, inject/src/main/java/io/avaje/inject/Lazy.java, inject/src/main/java/io/avaje/inject/spi/Builder.java, inject/src/main/java/io/avaje/inject/spi/DContextEntryBean.java, inject/src/main/java/io/avaje/inject/spi/OnceProvider.java
Now will generate proxy classes for true laziness in the following situations with `@Lazy` beans:
- class with a no-arg constructor
- factory bean method returning a class with a no-arg constructor
- class without a no-arg constructor, but a `@BeanTypes` class that is an interface or has a no arg constructor
- same as above but with factory bean methods
- factory method, but an interface is the return type
given the following class:
```java
@Lazy
@Singleton
public class LazyBean {
Provider<Integer> intProvider;
public LazyBean() {}
@Inject
public LazyBean(Provider<Integer> intProvider) {
this.intProvider = intProvider;
}
public LazyBean() {}
void something() {}
}
```
the following proxy class is generated:
```java
@Proxy
@Generated("avaje-inject-generator")
public final class …
```
=> Generate Compile Time Proxies for certain `@Lazy` beans

blackbox-test-inject/src/main/java/org/example/myapp/generic/MyUseGenericDependencies.java, blackbox-test-inject/src/test/java/org/example/myapp/generic/GenericFactoryTest.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java
Had a problem in the Discord where a multi-module project failed to work because it couldn't retrieve all the implementations of a generic type.
- now generic super types will be added to the bean entry
=> Register Generic Supertype as an Injectable Type

inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java
Now will pinpoint the exact missing dependency in the error message when external beans are involved.
before given class
```java
@Singleton
public class ExternalDeps {
@Inject @Nullable AtomicLong longy;
public ExternalDeps(AtomicBoolean bool, @External AtomicInteger inty) {}
}
```
it would error with 
```
Dependencies [java.util.concurrent.atomic.AtomicBoolean, java.util.concurrent.atomic.AtomicInteger] are not provided
```
Now it will correctly error with 
```
Dependencies [java.util.concurrent.atomic.AtomicBoolean] are not provided
```
=> Fix external dependency error messages

README.md, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject/src/main/java/io/avaje/inject/Lazy.java
Now warns on compilation if missing a no-args constructor
=> Add Compile Warnings to Use Lazy Correctly

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-test/src/test/java/io/avaje/inject/xtra/SystemContextTest.java, inject-test/src/test/java/org/example/coffee/CoffeeMakerTest.java, inject-test/src/test/java/org/example/coffee/priority/base/PriorityFactory.java, inject-test/src/test/java/org/example/coffee/priority/base/PriorityTest.java, inject/src/main/java/io/avaje/inject/BeanEntry.java, inject/src/main/java/io/avaje/inject/BeanScope.java, inject/src/main/java/io/avaje/inject/Priority.java, inject/src/main/java/io/avaje/inject/spi/Builder.java, inject/src/main/java/io/avaje/inject/spi/DBeanMap.java, inject/src/main/java/io/avaje/inject/spi/DBeanScope.java, inject/src/main/java/io/avaje/inject/spi/DBeanScopeProxy.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java, inject/src/main/java/io/avaje/inject/spi/DContextEntry.java, inject/src/main/java/io/avaje/inject/spi/DContextEntryBean.java, inject/src/test/java/io/avaje/inject/BeanScopeBuilderTest.java
- read the `@Priority` annotations at compile time
- listByPriority will now sort `@Primary`/`@Secondary` beans
- simplify duplicate type matching logic
- Add support for using `@Priority` on factory `@Bean` methods
Resolves #854
=> Determine Priority Annotations at Compile Time

inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject/src/main/java/io/avaje/inject/spi/AvajeModule.java
Honestly, there is no reason to split into three separate methods, given that we support generic wiring.
- deprecates auto requires/provides
- generate only provides/requires
- move the generation order such that the build method is seen first. (got tired of scrolling past the massive classes/provides to see the wiring logic)
=> Merge requires/provides with their auto variants

inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java, inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java, inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java, inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java, inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/UtilTest.java, inject/src/main/java/io/avaje/inject/spi/DependencyMeta.java
similar to https://github.com/avaje/avaje-inject/pull/851 merge auto/aspect provides into `provides`.
Doing this also replicated the issue in #868 that necessitated beantypes, so this resolves that as well.
=> Remove Auto Provides from `@DependencyMeta`

blackbox-multi-scope/src/main/java/org/multi/parents/BeanIn4.java, blackbox-multi-scope/src/test/java/org/multi/parents/ParentageTest.java, inject/src/main/java/io/avaje/inject/spi/DBuilder.java
Apparently when I did #873 I missed that `DBuilder` didn't check the parent scope when calling `contains`... sorry!
=> DBuilder contains checking parent if present

blackbox-test-inject/src/main/java/org/example/myapp/lazy2/LazyOneA.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy2/LazyOneB.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy2/LazyTwo.java, blackbox-test-inject/src/main/java/org/example/myapp/lazy2/package-info.java, blackbox-test-inject/src/test/java/org/example/myapp/lazy2/LazyTwoTest.java, inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java, inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject/src/main/java/io/avaje/inject/Lazy.java
Given that we generate proxies at compile time, this technically works.
- Lazy can now be placed on module/package info
- adds a flag to enforce proxy generation
Resolves: https://github.com/avaje/avaje-inject/pull/692
=> Make `@Lazy` work on a package/module level

inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanLazyWriter.java, inject-generator/src/main/java/io/avaje/inject/generator/Util.java, inject-generator/src/test/java/io/avaje/inject/generator/models/valid/lazy/LazyBean.java
- skip compile proxy on type with single no arg constructor with a checked exception
- import thrown method exceptions on generated lazy class
resolves #900
=> Fix Lazy Imports on Thrown Exceptions
